version: '3'

tasks:
  proto:
    desc: Generate gRPC protobuf files
    cmds:
      - protoc -I proto proto/*.proto --go_out=pb --go_opt=paths=source_relative --go-grpc_out=pb --go-grpc_opt=paths=source_relative

  clean:
    desc: Delete generated pb files
    cmds:
      - rm -f pb/*.pb.go
