version: '3'

tasks:
  gen:user:
    cmds:
      - cd ../user && protoc -I proto proto/user.proto 
        --go_out=pb --go_opt=paths=source_relative 
        --go-grpc_out=pb --go-grpc_opt=paths=source_relative

  gen:book:
    cmds:
      - cd ../book && protoc -I proto proto/book.proto 
        --go_out=pb --go_opt=paths=source_relative 
        --go-grpc_out=pb --go-grpc_opt=paths=source_relative

  gen:userbook:
    cmds:
      - cd ../userbook && protoc -I proto proto/userbook.proto 
        --go_out=pb --go_opt=paths=source_relative 
        --go-grpc_out=pb --go-grpc_opt=paths=source_relative

  gen:auth:
    cmds:
      - cd ../auth && protoc -I proto proto/auth.proto
        --go_out=pb --go_opt=paths=source_relative
        --go-grpc_out=pb --go-grpc_opt=paths=source_relative

  gen:all:
    deps: [gen:user, gen:book, gen:userbook ,gen:auth]
