// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: library.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_library_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AddBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBookRequest) Reset() {
	*x = AddBookRequest{}
	mi := &file_library_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBookRequest) ProtoMessage() {}

func (x *AddBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBookRequest.ProtoReflect.Descriptor instead.
func (*AddBookRequest) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{1}
}

func (x *AddBookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddBookRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type BorrowBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId        int32                  `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorrowBookRequest) Reset() {
	*x = BorrowBookRequest{}
	mi := &file_library_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorrowBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowBookRequest) ProtoMessage() {}

func (x *BorrowBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowBookRequest.ProtoReflect.Descriptor instead.
func (*BorrowBookRequest) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{2}
}

func (x *BorrowBookRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BorrowBookRequest) GetBookId() int32 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_library_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{3}
}

func (x *UserID) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_library_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{4}
}

func (x *UserResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type BookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookResponse) Reset() {
	*x = BookResponse{}
	mi := &file_library_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookResponse) ProtoMessage() {}

func (x *BookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookResponse.ProtoReflect.Descriptor instead.
func (*BookResponse) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{5}
}

func (x *BookResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BookResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type BorrowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorrowResponse) Reset() {
	*x = BorrowResponse{}
	mi := &file_library_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorrowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowResponse) ProtoMessage() {}

func (x *BorrowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowResponse.ProtoReflect.Descriptor instead.
func (*BorrowResponse) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{6}
}

func (x *BorrowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BookListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*BookResponse        `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookListResponse) Reset() {
	*x = BookListResponse{}
	mi := &file_library_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookListResponse) ProtoMessage() {}

func (x *BookListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookListResponse.ProtoReflect.Descriptor instead.
func (*BookListResponse) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{7}
}

func (x *BookListResponse) GetBooks() []*BookResponse {
	if x != nil {
		return x.Books
	}
	return nil
}

type UploadSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSummary) Reset() {
	*x = UploadSummary{}
	mi := &file_library_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSummary) ProtoMessage() {}

func (x *UploadSummary) ProtoReflect() protoreflect.Message {
	mi := &file_library_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSummary.ProtoReflect.Descriptor instead.
func (*UploadSummary) Descriptor() ([]byte, []int) {
	return file_library_proto_rawDescGZIP(), []int{8}
}

func (x *UploadSummary) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_library_proto protoreflect.FileDescriptor

const file_library_proto_rawDesc = "" +
	"\n" +
	"\rlibrary.proto\x12\alibrary\x1a\x1bgoogle/protobuf/empty.proto\"?\n" +
	"\x13RegisterUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\">\n" +
	"\x0eAddBookRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\"E\n" +
	"\x11BorrowBookRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\x05R\x06bookId\"!\n" +
	"\x06UserID\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"H\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"L\n" +
	"\fBookResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\"*\n" +
	"\x0eBorrowResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"?\n" +
	"\x10BookListResponse\x12+\n" +
	"\x05books\x18\x01 \x03(\v2\x15.library.BookResponseR\x05books\"%\n" +
	"\rUploadSummary\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count2\xd6\x03\n" +
	"\x0eLibraryService\x12C\n" +
	"\fRegisterUser\x12\x1c.library.RegisterUserRequest\x1a\x15.library.UserResponse\x129\n" +
	"\aAddBook\x12\x17.library.AddBookRequest\x1a\x15.library.BookResponse\x12A\n" +
	"\n" +
	"BorrowBook\x12\x1a.library.BorrowBookRequest\x1a\x17.library.BorrowResponse\x12A\n" +
	"\n" +
	"ReturnBook\x12\x1a.library.BorrowBookRequest\x1a\x17.library.BorrowResponse\x12;\n" +
	"\rListUserBooks\x12\x0f.library.UserID\x1a\x19.library.BookListResponse\x12?\n" +
	"\fListAllBooks\x12\x16.google.protobuf.Empty\x1a\x15.library.BookResponse0\x01\x12@\n" +
	"\vUploadBooks\x12\x17.library.AddBookRequest\x1a\x16.library.UploadSummary(\x01B(Z&github.com/TAhirr01/grpc-library/pb;pbb\x06proto3"

var (
	file_library_proto_rawDescOnce sync.Once
	file_library_proto_rawDescData []byte
)

func file_library_proto_rawDescGZIP() []byte {
	file_library_proto_rawDescOnce.Do(func() {
		file_library_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_library_proto_rawDesc), len(file_library_proto_rawDesc)))
	})
	return file_library_proto_rawDescData
}

var file_library_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_library_proto_goTypes = []any{
	(*RegisterUserRequest)(nil), // 0: library.RegisterUserRequest
	(*AddBookRequest)(nil),      // 1: library.AddBookRequest
	(*BorrowBookRequest)(nil),   // 2: library.BorrowBookRequest
	(*UserID)(nil),              // 3: library.UserID
	(*UserResponse)(nil),        // 4: library.UserResponse
	(*BookResponse)(nil),        // 5: library.BookResponse
	(*BorrowResponse)(nil),      // 6: library.BorrowResponse
	(*BookListResponse)(nil),    // 7: library.BookListResponse
	(*UploadSummary)(nil),       // 8: library.UploadSummary
	(*emptypb.Empty)(nil),       // 9: google.protobuf.Empty
}
var file_library_proto_depIdxs = []int32{
	5, // 0: library.BookListResponse.books:type_name -> library.BookResponse
	0, // 1: library.LibraryService.RegisterUser:input_type -> library.RegisterUserRequest
	1, // 2: library.LibraryService.AddBook:input_type -> library.AddBookRequest
	2, // 3: library.LibraryService.BorrowBook:input_type -> library.BorrowBookRequest
	2, // 4: library.LibraryService.ReturnBook:input_type -> library.BorrowBookRequest
	3, // 5: library.LibraryService.ListUserBooks:input_type -> library.UserID
	9, // 6: library.LibraryService.ListAllBooks:input_type -> google.protobuf.Empty
	1, // 7: library.LibraryService.UploadBooks:input_type -> library.AddBookRequest
	4, // 8: library.LibraryService.RegisterUser:output_type -> library.UserResponse
	5, // 9: library.LibraryService.AddBook:output_type -> library.BookResponse
	6, // 10: library.LibraryService.BorrowBook:output_type -> library.BorrowResponse
	6, // 11: library.LibraryService.ReturnBook:output_type -> library.BorrowResponse
	7, // 12: library.LibraryService.ListUserBooks:output_type -> library.BookListResponse
	5, // 13: library.LibraryService.ListAllBooks:output_type -> library.BookResponse
	8, // 14: library.LibraryService.UploadBooks:output_type -> library.UploadSummary
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_library_proto_init() }
func file_library_proto_init() {
	if File_library_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_library_proto_rawDesc), len(file_library_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_library_proto_goTypes,
		DependencyIndexes: file_library_proto_depIdxs,
		MessageInfos:      file_library_proto_msgTypes,
	}.Build()
	File_library_proto = out.File
	file_library_proto_goTypes = nil
	file_library_proto_depIdxs = nil
}
