// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: userbook.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BorrowBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId        int32                  `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorrowBookRequest) Reset() {
	*x = BorrowBookRequest{}
	mi := &file_userbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorrowBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowBookRequest) ProtoMessage() {}

func (x *BorrowBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowBookRequest.ProtoReflect.Descriptor instead.
func (*BorrowBookRequest) Descriptor() ([]byte, []int) {
	return file_userbook_proto_rawDescGZIP(), []int{0}
}

func (x *BorrowBookRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BorrowBookRequest) GetBookId() int32 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type BorrowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorrowResponse) Reset() {
	*x = BorrowResponse{}
	mi := &file_userbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorrowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowResponse) ProtoMessage() {}

func (x *BorrowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowResponse.ProtoReflect.Descriptor instead.
func (*BorrowResponse) Descriptor() ([]byte, []int) {
	return file_userbook_proto_rawDescGZIP(), []int{1}
}

func (x *BorrowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_userbook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_userbook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_userbook_proto_rawDescGZIP(), []int{2}
}

func (x *UserID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookResponse) Reset() {
	*x = BookResponse{}
	mi := &file_userbook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookResponse) ProtoMessage() {}

func (x *BookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userbook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookResponse.ProtoReflect.Descriptor instead.
func (*BookResponse) Descriptor() ([]byte, []int) {
	return file_userbook_proto_rawDescGZIP(), []int{3}
}

func (x *BookResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BookResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

var File_userbook_proto protoreflect.FileDescriptor

const file_userbook_proto_rawDesc = "" +
	"\n" +
	"\x0euserbook.proto\"E\n" +
	"\x11BorrowBookRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\x05R\x06bookId\"*\n" +
	"\x0eBorrowResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x18\n" +
	"\x06UserID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"L\n" +
	"\fBookResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author2\xa5\x01\n" +
	"\x0fUserBookService\x121\n" +
	"\n" +
	"BorrowBook\x12\x12.BorrowBookRequest\x1a\x0f.BorrowResponse\x121\n" +
	"\n" +
	"ReturnBook\x12\x12.BorrowBookRequest\x1a\x0f.BorrowResponse\x12,\n" +
	"\x10ListAllUserBooks\x12\a.UserID\x1a\r.BookResponse0\x01B(Z&github.com/TAhirr01/grpc-library/pb;pbb\x06proto3"

var (
	file_userbook_proto_rawDescOnce sync.Once
	file_userbook_proto_rawDescData []byte
)

func file_userbook_proto_rawDescGZIP() []byte {
	file_userbook_proto_rawDescOnce.Do(func() {
		file_userbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userbook_proto_rawDesc), len(file_userbook_proto_rawDesc)))
	})
	return file_userbook_proto_rawDescData
}

var file_userbook_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_userbook_proto_goTypes = []any{
	(*BorrowBookRequest)(nil), // 0: BorrowBookRequest
	(*BorrowResponse)(nil),    // 1: BorrowResponse
	(*UserID)(nil),            // 2: UserID
	(*BookResponse)(nil),      // 3: BookResponse
}
var file_userbook_proto_depIdxs = []int32{
	0, // 0: UserBookService.BorrowBook:input_type -> BorrowBookRequest
	0, // 1: UserBookService.ReturnBook:input_type -> BorrowBookRequest
	2, // 2: UserBookService.ListAllUserBooks:input_type -> UserID
	1, // 3: UserBookService.BorrowBook:output_type -> BorrowResponse
	1, // 4: UserBookService.ReturnBook:output_type -> BorrowResponse
	3, // 5: UserBookService.ListAllUserBooks:output_type -> BookResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_userbook_proto_init() }
func file_userbook_proto_init() {
	if File_userbook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userbook_proto_rawDesc), len(file_userbook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userbook_proto_goTypes,
		DependencyIndexes: file_userbook_proto_depIdxs,
		MessageInfos:      file_userbook_proto_msgTypes,
	}.Build()
	File_userbook_proto = out.File
	file_userbook_proto_goTypes = nil
	file_userbook_proto_depIdxs = nil
}
